spring.application.name=java-ecommerce

# Connection Pooling:
# Maximum number of idle connections kept in the pool -> should match the number of CPU cores (max.)
spring.datasource.hikari.maximum-pool-size=10
# How long a connection can sit idle before being retired
spring.datasource.hikari.idle-timeout=30000

# Query Analysis
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# This shows the actual values (e.g., 'Berlin') instead of '?'
logging.level.org.hibernate.orm.jdbc.bind=trace

# Standardized error responses for HTTP APIs (Standardized JSON Structure for error details, Automatic Exception Handling, specialized Media Type):
spring.mvc.problemdetails.enabled=true